exp_res_t expression(int level, int *ptx, exp_res_t wanted, tag_t tag);
exp_res_t expression_raw(int level, int *ptx, tag_t tag);
exp_res_t expression_shift(int level, int *ptx, tag_t tag);
exp_res_t expression_and_or(int level, int *ptx, tag_t tag);
exp_res_t expression_operand(int level, int *ptx, tag_t tag);
exp_res_t expression_arraydef(int level, int *ptx, tag_t tag);
exp_res_t expression_plus_minus(int level, int *ptx, tag_t tag);
exp_res_t expression_ref(int level, int *ptx, tag_t tag, BOOL ref);
exp_res_t expression_ident_unary(int level, int *ptx, exp_res_t current_res);
exp_res_t expression_pure_array_element(identinfo_t *ident_p, int level, int *ptx, BOOL aggregate);
exp_res_t expression_condition_worker(int level, int *ptx, exp_res_t exp_current, BOOL for_case, processing_fn pfn, tag_t tag);
exp_res_t expression_cast_op(processing_fn fn, int level, int *ptx, int operation, exp_res_t current_res, tag_t tag);
exp_res_t expression_array_element(identinfo_t *ident_p, int level, int *ptx, BOOL aggregate, BOOL push);
exp_res_t expression_unary(identinfo_t *ident_p, int symbol, int level, int *ptx, exp_res_t current_res, BOOL left);
exp_res_t expression_bitwise(int level, int *ptx, tag_t tag);
exp_res_t expression_ident(int level, int *ptx, tag_t tag);
exp_res_t expression_unary_left(int level, int *ptx, tag_t tag);
exp_res_t expression_inlineif(int level, int *ptx, tag_t tag);
exp_res_t expression_condition(int level, int *ptx, tag_t tag);
exp_res_t expression_term(int level, int *ptx, tag_t tag);
exp_res_t expression_string_condition(int level, int *ptx, tag_t tag);
exp_res_t expression_ident_array_unary(int level, int *ptx, exp_res_t current_res);